# 网关配置
server:
  port: 8080

spring:
  application:
    name: yt-base-gateway
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
    gateway:
      routes:
        # OCR服务路由
        - id: yt-base-ocr
          uri: lb://yt-base-ocr
          predicates:
            - Path=/api/ocr/**
          filters:
            - StripPrefix=1
        
        # 推送服务路由
        - id: yt-base-push
          uri: lb://yt-base-push
          predicates:
            - Path=/api/push/**
          filters:
            - StripPrefix=1
        
        # 对象存储服务路由
        - id: yt-base-storage
          uri: lb://yt-base-storage
          predicates:
            - Path=/api/storage/**
          filters:
            - StripPrefix=1
      
      # 全局CORS配置
      globalcors:
        cors-configurations:
          '[/**]':
            allowed-origins: "*"
            allowed-methods: "*"
            allowed-headers: "*"
            allow-credentials: true
      
      # 默认过滤器
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
  redis:
    host: localhost
    port: 6379
    password: 
    database: 3
    timeout: 3000ms
    lettuce:
      pool:
        max-active: 8
        max-idle: 8
        min-idle: 0

# 日志配置
logging:
  level:
    com.yitong.base: debug
    org.springframework.cloud.gateway: debug
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"