# 网关配置
server:
  port: 8080

spring:
  application:
    name: yt-base-gateway
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
        enabled: false  # 禁用Nacos服务发现
    gateway:
      discovery:
        locator:
          enabled: false  # 禁用服务发现路由
      routes:
        # OCR服务路由 - 使用直接URL而不是负载均衡
        - id: yt-base-ocr
          uri: http://localhost:8081
          predicates:
            - Path=/api/ocr/**
          filters:
            - StripPrefix=1
        
        # 推送服务路由
        - id: yt-base-push
          uri: http://localhost:8082
          predicates:
            - Path=/api/push/**
          filters:
            - StripPrefix=1
        
        # 对象存储服务路由
        - id: yt-base-storage
          uri: http://localhost:8083
          predicates:
            - Path=/api/storage/**
          filters:
            - StripPrefix=1
      
      # 全局CORS配置
      globalcors:
        cors-configurations:
          '[/**]':
            allowed-origins: "*"
            allowed-methods: "*"
            allowed-headers: "*"
            allow-credentials: true
      
      # 默认过滤器
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
  data:
    redis:
      host: localhost
      port: 6379
      password: 
      database: 3
      timeout: 3000ms
      lettuce:
        pool:
          max-active: 8
          max-idle: 8
          min-idle: 0

# 日志配置
logging:
  level:
    com.yitong.base: debug
    org.springframework.cloud.gateway: debug
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"