# 网关配置
server:
  port: 8080

spring:
  application:
    name: yt-base-gateway
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.110.121:8848
        namespace: 8bab8359-d8ab-44e2-9400-862f93a8a1c2
        username: nacos
        password: zqzx12138
    gateway:
      routes:
        # OCR服务路由
        - id: yt-base-ocr
          uri: lb://yt-base-ocr
          predicates:
            - Path=/base-api/ocr/**
          filters:
            - StripPrefix=1
        
        # 推送服务路由
        - id: yt-base-push
          uri: lb://yt-base-push
          predicates:
            - Path=/base-api/push/**
          filters:
            - StripPrefix=1
        
        # 对象存储服务路由
        - id: yt-base-storage
          uri: lb://yt-base-storage
          predicates:
            - Path=/base-api/storage/**
          filters:
            - StripPrefix=1
      
      # 全局CORS配置
      globalcors:
        cors-configurations:
          '[/**]':
            allowed-origins: "*"
            allowed-methods: "*"
            allowed-headers: "*"
            allow-credentials: true
      
      # 默认过滤器
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
  data:
    redis:
      sentinel:
        master: mymaster
        password: SenTinel@pwd
        nodes:
        - 192.168.110.205:26380
        - 192.168.110.206:26380
        - 192.168.110.207:26380
      password: SenTinel@pwd
      database: 0
      timeout: 3000ms
      lettuce:
        pool:
          max-active: 8
          max-idle: 8
          min-idle: 0

# 日志配置
logging:
  level:
    com.yitong.base: debug
    org.springframework.cloud.gateway: debug
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"